// src/components/HelloWorld.vue
<template>
    <div class="main">
        <h1>Andreas Mikko</h1>
        <p>This site is under construction.</p>
        <p>
            In the meanwhile visit my
            <a href="https://www.linkedin.com/in/andreas-mikko-04ab9988/"
                >LinkedIn page</a
            >.
        </p>
    </div>
</template>

<style scoped>
.main {
    position: relative;
    background-color: rgba(0, 0, 0, 0.3);
    padding: 0.5rem;
    border-radius: 10px;
}
</style>

// src/components/HelloWorld.tsx
import "./HelloWorld.css";

export const HelloWorld = () => {
    return (
        <div className="main">
            <h1>Andreas Mikko</h1>
            <p>This site is under construction.</p>
            <p>
                In the meanwhile visit my{" "}
                <a href="https://www.linkedin.com/in/andreas-mikko-04ab9988/">
                    LinkedIn page
                </a>
                .
            </p>
        </div>
    );
};
